package discovery

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pmclSF/gauntlet/internal/iopairs"
	"github.com/pmclSF/gauntlet/internal/scenario"
	"github.com/pmclSF/gauntlet/internal/world"
	"gopkg.in/yaml.v3"
)

const autoGeneratedHeader = "# gauntlet:auto-generated"

// AutoSuiteConfig configures automatic discovery and suite generation.
type AutoSuiteConfig struct {
	RootDir       string
	EvalsDir      string
	Suite         string
	SuiteDir      string
	ToolsDir      string
	DBDir         string
	PairsDir      string
	ProposalsPath string
	PythonDirs    []string
	ExcludeTools  []string
	Force         bool
}

// AutoSuiteResult reports what auto-discovery generated.
type AutoSuiteResult struct {
	ProposalsCount     int
	GeneratedScenarios int
	Skipped            bool
	SkipReason         string
}

// EnsureAutoSuite refreshes discovery proposals and generates auto scenarios.
// It will not overwrite manually-authored scenarios unless Force is true.
func EnsureAutoSuite(cfg AutoSuiteConfig) (*AutoSuiteResult, error) {
	cfg = normalizeAutoSuiteConfig(cfg)
	result := &AutoSuiteResult{}

	engine := NewEngine(DiscoveryConfig{
		RootDir:      cfg.RootDir,
		ToolDirs:     []string{cfg.ToolsDir},
		PythonDirs:   cfg.PythonDirs,
		DBSchemaDir:  cfg.DBDir,
		ExcludeTools: cfg.ExcludeTools,
	})
	proposals, err := engine.Discover()
	if err != nil {
		return nil, err
	}
	applyExistingProposalStatuses(cfg.ProposalsPath, proposals)
	if err := os.MkdirAll(filepath.Dir(cfg.ProposalsPath), 0o755); err != nil {
		return nil, fmt.Errorf("failed to create proposals directory: %w", err)
	}
	if err := SaveProposals(proposals, cfg.ProposalsPath); err != nil {
		return nil, err
	}
	result.ProposalsCount = len(proposals)

	manualFiles, autoFiles, err := inspectSuiteFiles(cfg.SuiteDir)
	if err != nil {
		return nil, err
	}
	if len(manualFiles) > 0 && !cfg.Force {
		result.Skipped = true
		result.SkipReason = "manual scenarios present; use --discover-force to regenerate"
		return result, nil
	}

	// Hash-based staleness check: skip regeneration if inputs haven't changed.
	inputHash := computeInputHash(cfg.ToolsDir, cfg.DBDir, cfg.PairsDir, proposals)
	hashPath := filepath.Join(cfg.SuiteDir, ".gauntlet-auto-hash")
	if !cfg.Force && len(autoFiles) > 0 {
		if stored, err := os.ReadFile(hashPath); err == nil && string(stored) == inputHash {
			result.Skipped = true
			result.SkipReason = "auto-generated scenarios are up to date"
			return result, nil
		}
	}

	ws, err := world.Assemble(cfg.ToolsDir, cfg.DBDir, nil, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to load world definitions for auto scenarios: %w", err)
	}
	pairByTool := loadPairLibrariesByTool(cfg.PairsDir)

	docs := buildAutoScenarioDocs(cfg.Suite, proposals, ws, pairByTool)
	if len(docs) == 0 {
		if len(manualFiles) > 0 {
			result.Skipped = true
			result.SkipReason = "no auto scenarios discovered"
			return result, nil
		}
		return nil, fmt.Errorf("no auto scenarios discovered; add tool/db definitions or run with an explicit suite")
	}
	if err := validateAutoScenarioDocs(docs); err != nil {
		return nil, err
	}

	if err := os.MkdirAll(cfg.SuiteDir, 0o755); err != nil {
		return nil, fmt.Errorf("failed to create suite directory %s: %w", cfg.SuiteDir, err)
	}
	if err := removeFiles(autoFiles); err != nil {
		return nil, err
	}
	for _, doc := range docs {
		if err := writeAutoScenarioDoc(cfg.SuiteDir, doc); err != nil {
			return nil, err
		}
	}
	result.GeneratedScenarios = len(docs)

	// Persist hash for staleness detection on next run.
	os.WriteFile(hashPath, []byte(inputHash), 0o644)

	return result, nil
}

func normalizeAutoSuiteConfig(cfg AutoSuiteConfig) AutoSuiteConfig {
	if strings.TrimSpace(cfg.RootDir) == "" {
		cfg.RootDir = "."
	}
	if strings.TrimSpace(cfg.EvalsDir) == "" {
		cfg.EvalsDir = "evals"
	}
	if strings.TrimSpace(cfg.Suite) == "" {
		cfg.Suite = "smoke"
	}
	if strings.TrimSpace(cfg.SuiteDir) == "" {
		cfg.SuiteDir = filepath.Join(cfg.EvalsDir, cfg.Suite)
	}
	if strings.TrimSpace(cfg.ToolsDir) == "" {
		cfg.ToolsDir = filepath.Join(cfg.EvalsDir, "world", "tools")
	}
	if strings.TrimSpace(cfg.DBDir) == "" {
		cfg.DBDir = filepath.Join(cfg.EvalsDir, "world", "databases")
	}
	if strings.TrimSpace(cfg.PairsDir) == "" {
		cfg.PairsDir = filepath.Join(cfg.EvalsDir, "pairs")
	}
	if strings.TrimSpace(cfg.ProposalsPath) == "" {
		cfg.ProposalsPath = filepath.Join(cfg.EvalsDir, "proposals.yaml")
	}
	if len(cfg.PythonDirs) == 0 {
		cfg.PythonDirs = []string{"."}
	}
	return cfg
}

func applyExistingProposalStatuses(path string, proposals []Proposal) {
	if path == "" {
		return
	}
	existing, err := LoadProposals(path)
	if err != nil {
		return
	}
	statusByID := make(map[string]string, len(existing))
	for _, p := range existing {
		switch p.Status {
		case "pending", "approved", "rejected":
			statusByID[p.ID] = p.Status
		}
	}
	for i := range proposals {
		if status, ok := statusByID[proposals[i].ID]; ok {
			proposals[i].Status = status
		}
	}
}

// computeInputHash returns a deterministic hash over all discovery inputs
// (proposals, tool defs, DB defs, IO pairs) so we can detect staleness.
func computeInputHash(toolsDir, dbDir, pairsDir string, proposals []Proposal) string {
	h := sha256.New()

	// Hash sorted proposal IDs.
	ids := make([]string, len(proposals))
	for i, p := range proposals {
		ids[i] = p.ID
	}
	sort.Strings(ids)
	for _, id := range ids {
		h.Write([]byte(id))
	}

	// Hash modification times of all definition files.
	for _, dir := range []string{toolsDir, dbDir, pairsDir} {
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			info, err := e.Info()
			if err != nil {
				continue
			}
			h.Write([]byte(e.Name()))
			h.Write([]byte(info.ModTime().String()))
		}
	}

	return hex.EncodeToString(h.Sum(nil))
}

func inspectSuiteFiles(suiteDir string) (manualFiles []string, autoFiles []string, err error) {
	entries, err := os.ReadDir(suiteDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil, nil
		}
		return nil, nil, fmt.Errorf("failed to read suite directory %s: %w", suiteDir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".yaml") && !strings.HasSuffix(name, ".yml") {
			continue
		}
		path := filepath.Join(suiteDir, name)
		if isAutoGeneratedFile(path) {
			autoFiles = append(autoFiles, path)
			continue
		}
		manualFiles = append(manualFiles, path)
	}
	sort.Strings(manualFiles)
	sort.Strings(autoFiles)
	return manualFiles, autoFiles, nil
}

// isAutoGeneratedFile checks if a YAML file starts with the auto-generated header.
// Falls back to filename prefix for backwards compatibility.
func isAutoGeneratedFile(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return strings.HasPrefix(filepath.Base(path), "auto_")
	}
	content := string(data)
	if strings.HasPrefix(content, autoGeneratedHeader) {
		return true
	}
	return strings.HasPrefix(filepath.Base(path), "auto_")
}

func removeFiles(paths []string) error {
	for _, p := range paths {
		if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove %s: %w", p, err)
		}
	}
	return nil
}

func loadPairLibrariesByTool(dir string) map[string]*iopairs.Library {
	libs, err := iopairs.LoadLibrariesFromDir(dir)
	if err != nil || len(libs) == 0 {
		return map[string]*iopairs.Library{}
	}
	byTool := map[string]*iopairs.Library{}
	for _, lib := range libs {
		if lib == nil || strings.TrimSpace(lib.Tool) == "" {
			continue
		}
		tool := strings.TrimSpace(lib.Tool)
		if existing, ok := byTool[tool]; ok {
			if len(lib.GoodPairs()) > len(existing.GoodPairs()) {
				byTool[tool] = lib
			}
			continue
		}
		byTool[tool] = lib
	}
	return byTool
}

type autoScenarioDoc struct {
	Scenario    string                   `yaml:"scenario"`
	Description string                   `yaml:"description,omitempty"`
	Tags        []string                 `yaml:"tags,omitempty"`
	Input       autoInputDoc             `yaml:"input"`
	World       autoWorldDoc             `yaml:"world"`
	Assertions  []map[string]interface{} `yaml:"assertions,omitempty"`
}

type autoInputDoc struct {
	Messages []autoMessageDoc `yaml:"messages,omitempty"`
}

type autoMessageDoc struct {
	Role    string `yaml:"role"`
	Content string `yaml:"content"`
}

type autoWorldDoc struct {
	Tools     map[string]string      `yaml:"tools,omitempty"`
	Databases map[string]interface{} `yaml:"databases,omitempty"`
}

func buildAutoScenarioDocs(suite string, proposals []Proposal, ws *world.State, pairByTool map[string]*iopairs.Library) []autoScenarioDoc {
	nominalTools := nominalToolStates(ws)
	sorted := append([]Proposal{}, proposals...)
	sort.SliceStable(sorted, func(i, j int) bool {
		ki := proposalKey(sorted[i])
		kj := proposalKey(sorted[j])
		if ki != kj {
			return ki < kj
		}
		return sorted[i].ID < sorted[j].ID
	})

	seen := map[string]bool{}
	var docs []autoScenarioDoc
	for _, p := range sorted {
		switch {
		case p.Tool != "":
			variant := strings.TrimSpace(p.Variant)
			if variant == "" {
				variant = "nominal"
			}
			name := sanitizeScenarioName(fmt.Sprintf("auto_tool_%s_%s", p.Tool, variant))
			if seen[name] {
				continue
			}
			seen[name] = true
			tools := cloneToolStates(nominalTools)
			tools[p.Tool] = variant
			doc := autoScenarioDoc{
				Scenario:    name,
				Description: fmt.Sprintf("Auto-generated %s scenario for tool %s in state %s", suite, p.Tool, variant),
				Tags:        []string{"auto-generated", "auto-discovered", "tool-permutation"},
				Input: autoInputDoc{
					Messages: []autoMessageDoc{{
						Role:    "user",
						Content: toolPrompt(p.Tool, pairByTool[p.Tool]),
					}},
				},
				World: autoWorldDoc{
					Tools: tools,
				},
				Assertions: []map[string]interface{}{
					{
						"type":     "tool_sequence",
						"required": []string{p.Tool},
					},
					{
						"type":        "retry_cap",
						"tool":        p.Tool,
						"max_retries": 3,
					},
					{
						"type": "sensitive_leak",
					},
				},
			}
			docs = append(docs, doc)
		case p.Database != "":
			seed := strings.TrimSpace(p.SeedSet)
			if seed == "" {
				continue
			}
			name := sanitizeScenarioName(fmt.Sprintf("auto_db_%s_%s", p.Database, seed))
			if seen[name] {
				continue
			}
			seen[name] = true
			tools := cloneToolStates(nominalTools)
			targetTool := pickToolForDB(p.Database, tools, pairByTool)
			assertions := []map[string]interface{}{
				{
					"type": "sensitive_leak",
				},
			}
			if targetTool != "" {
				assertions = append([]map[string]interface{}{
					{
						"type":     "tool_sequence",
						"required": []string{targetTool},
					},
					{
						"type":        "retry_cap",
						"tool":        targetTool,
						"max_retries": 3,
					},
				}, assertions...)
			}
			doc := autoScenarioDoc{
				Scenario:    name,
				Description: fmt.Sprintf("Auto-generated %s scenario for database %s seed set %s", suite, p.Database, seed),
				Tags:        []string{"auto-generated", "auto-discovered", "db-permutation"},
				Input: autoInputDoc{
					Messages: []autoMessageDoc{{
						Role:    "user",
						Content: dbPrompt(p.Database, seed, targetTool),
					}},
				},
				World: autoWorldDoc{
					Tools: tools,
					Databases: map[string]interface{}{
						p.Database: seed,
					},
				},
				Assertions: assertions,
			}
			docs = append(docs, doc)
		}
	}
	return docs
}

func nominalToolStates(ws *world.State) map[string]string {
	out := map[string]string{}
	if ws == nil {
		return out
	}
	var names []string
	for name := range ws.Tools {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		td := ws.Tools[name]
		if td == nil || len(td.States) == 0 {
			continue
		}
		if _, ok := td.States["nominal"]; ok {
			out[name] = "nominal"
			continue
		}
		var states []string
		for s := range td.States {
			states = append(states, s)
		}
		sort.Strings(states)
		out[name] = states[0]
	}
	return out
}

func cloneToolStates(in map[string]string) map[string]string {
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func toolPrompt(tool string, lib *iopairs.Library) string {
	if lib != nil {
		good := lib.GoodPairs()
		if len(good) > 0 && len(good[0].Input) > 0 {
			if payload, err := json.Marshal(good[0].Input); err == nil {
				return fmt.Sprintf("Use tool %s with input %s and provide a concise response.", tool, string(payload))
			}
		}
	}
	return fmt.Sprintf("Use tool %s to handle this request and provide a concise response.", tool)
}

func dbPrompt(database, seedSet, tool string) string {
	if tool != "" {
		return fmt.Sprintf("Use tool %s while operating against database %s with seed set %s.", tool, database, seedSet)
	}
	return fmt.Sprintf("Answer this request while operating against database %s with seed set %s.", database, seedSet)
}

func pickToolForDB(database string, tools map[string]string, pairByTool map[string]*iopairs.Library) string {
	if len(tools) == 0 {
		return ""
	}
	base := strings.TrimSuffix(strings.ToLower(strings.TrimSpace(database)), "_db")
	base = strings.TrimSuffix(base, "s")
	var candidates []string
	for tool := range tools {
		candidates = append(candidates, tool)
	}
	sort.Strings(candidates)

	bestTool := ""
	bestScore := -1
	for _, tool := range candidates {
		score := 0
		tl := strings.ToLower(tool)
		if base != "" && (strings.Contains(tl, base) || strings.Contains(base, strings.TrimSuffix(tl, "s"))) {
			score += 3
		}
		if _, ok := pairByTool[tool]; ok {
			score += 1
		}
		if score > bestScore {
			bestScore = score
			bestTool = tool
		}
	}
	return bestTool
}

func sanitizeScenarioName(raw string) string {
	raw = strings.ToLower(strings.TrimSpace(raw))
	var b strings.Builder
	for _, r := range raw {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
			continue
		}
		if r == '-' || r == ' ' || r == '/' || r == '.' {
			b.WriteRune('_')
		}
	}
	out := strings.Trim(b.String(), "_")
	for strings.Contains(out, "__") {
		out = strings.ReplaceAll(out, "__", "_")
	}
	if out == "" {
		return "auto_scenario"
	}
	return out
}

func validateAutoScenarioDocs(docs []autoScenarioDoc) error {
	tmpDir, err := os.MkdirTemp("", "gauntlet-auto-scenarios-*")
	if err != nil {
		return fmt.Errorf("failed to create temp validation dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	for _, doc := range docs {
		data, err := yaml.Marshal(doc)
		if err != nil {
			return fmt.Errorf("failed to marshal generated scenario %s: %w", doc.Scenario, err)
		}
		path := filepath.Join(tmpDir, doc.Scenario+".yaml")
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return fmt.Errorf("failed to write temp generated scenario %s: %w", doc.Scenario, err)
		}
		if _, err := scenario.LoadFile(path); err != nil {
			return fmt.Errorf("generated scenario %s failed validation: %w", doc.Scenario, err)
		}
	}
	return nil
}

func writeAutoScenarioDoc(suiteDir string, doc autoScenarioDoc) error {
	data, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("failed to marshal generated scenario %s: %w", doc.Scenario, err)
	}
	content := autoGeneratedHeader + "\n# Generated by: gauntlet auto-discover\n\n" + string(data)
	path := filepath.Join(suiteDir, doc.Scenario+".yaml")

	// Atomic write: temp file + rename to prevent partial reads.
	tmp, err := os.CreateTemp(suiteDir, ".gauntlet-tmp-*.yaml")
	if err != nil {
		return fmt.Errorf("failed to create temp file for scenario %s: %w", doc.Scenario, err)
	}
	tmpPath := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("failed to write temp scenario %s: %w", doc.Scenario, err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("failed to close temp scenario %s: %w", doc.Scenario, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("failed to rename temp scenario %s: %w", doc.Scenario, err)
	}
	return nil
}
